Sct 76 modal validation
metlapp/scutl pull request #11
Opened 2021-01-08 21:31 UTC by JaycobDuffel

2021-01-08 22:20 UTC, DawsonDease approved these changes

2021-01-09 00:56 UTC, katiemcgoff commented on scutl.py
> +        "{}/organiztations/1/events/".format(os.environ.get("API_URL")),
typo in organizations

2021-01-09 01:00 UTC, DawsonDease commented on scutl.py
> +        "{}/organiztations/1/events/".format(os.environ.get("API_URL")),
good catch

2021-01-09 01:19 UTC, katiemcgoff commented on scutl.py
> +        "{}/organiztations/1/events/".format(os.environ.get("API_URL")),
Also - organization should be removed from data in this call as well.

2021-01-09 01:23 UTC, katiemcgoff requested changes
Manually tested, looks great.

2021-01-09 01:23 UTC, katiemcgoff approved these changes

2021-01-11 02:28 UTC, merged