Sct 69 list channels containing app
metlapp/scutl pull request #17
Opened 2021-01-15 18:29 UTC by DawsonDease

2021-01-15 19:54 UTC, JaycobDuffel approved these changes

2021-01-16 00:23 UTC, katiemcgoff commented on scutl.py
> +    channels = get_bot_channels(client, event["view"]["team_id"])
Tested it out, looks good. The only thing is that in this function we get the org, then in get_bot_channels() we get the org again. Let's cut that down. You could cut that down by having an optional parameter to get_bot_channels with the org.

2021-01-16 00:25 UTC, katiemcgoff commented on scutl.py
> +        channels_view['blocks'].extend(invite_message)
Should also show this message for ENTERPRISE tier.

2021-01-16 00:26 UTC, katiemcgoff requested changes
two changes requested

2021-01-20 17:59 UTC, katiemcgoff approved these changes

2021-01-20 19:08 UTC, merged