Sct 53 implement home layout
metlapp/scutl pull request #18
Opened 2021-01-18 19:46 UTC by JaycobDuffel

2021-01-19 15:28 UTC, katiemcgoff commented
Code looks good. When running, I found that the delay (running locally) getting Org from Metl API was too long and the trigger ID expired. However that's a universal problem and we need to evaluate it for our app on the whole. Out of scope of this ticket and may not be a problem when deployed.

However I did find one issue after overcoming the timing issue. When there are no single meetings and I add a new one, I get failure to update the list:
```
raise e.SlackRequestError("Either view_id or externa
l_id is required.")
slack_sdk.errors.SlackRequestError: Either view_id or ex
ternal_id is required.
```
Same with recurring - if there are no recurring events yet, and I add one, it fails to update the list. Upon navigating away and back, there is no issue.

2021-01-19 15:30 UTC, katiemcgoff commented on helpers/update_home.py
> +    )
Great work breaking up the code.

2021-01-19 15:31 UTC, katiemcgoff requested changes
One bug needs fixed.

2021-01-20 17:07 UTC, DawsonDease approved these changes

2021-01-20 17:56 UTC, katiemcgoff approved these changes

2021-01-20 17:57 UTC, merged