SCT-87
metlapp/scutl pull request #29
Opened 2021-01-29 20:49 UTC by DawsonDease

2021-02-01 15:27 UTC, JaycobDuffel approved these changes

2021-02-01 15:27 UTC, JaycobDuffel commented on scutl.py
> +        over_tier_limit = check_user_allotment(users, org)
Nice job refactoring this to a reusable function!

2021-02-01 17:12 UTC, DawsonDease commented on scutl.py
> +        over_tier_limit = check_user_allotment(users, org)
Thank you!

2021-02-01 17:34 UTC, katiemcgoff commented on scutl.py
> +            over_tier_limit = check_user_allotment(users, org)
This is really interesting code! I'm not sure I've ever used set() before. Looks good.

One thing - I believe the metl bot counts as a user in the new channel, so you should remove it before you check the user count.

2021-02-01 17:35 UTC, katiemcgoff requested changes
One change re. the bot user being counted in the user count.

2021-02-02 19:25 UTC, katiemcgoff approved these changes

2021-02-02 19:55 UTC, merged