Sct 101 redirect upon oauth success
metlapp/scutl pull request #31
Opened 2021-02-18 19:51 UTC by DawsonDease

2021-02-18 21:29 UTC, katiemcgoff commented on auth.py
> +    url = f"""{os.environ.get("API_URL")}/upgrading?app_id=
I don't think we want the API_URL (which would be api.metlapp.com or localhost:8000) but rather the webapp URL which is metlapp.com, or if you're developing locally, the react website running locally on some port.

2021-02-18 21:31 UTC, DawsonDease commented on auth.py
> +    url = f"""{os.environ.get("API_URL")}/upgrading?app_id=
oh yeah! Thats my bad

2021-02-18 21:33 UTC, katiemcgoff commented on auth.py
> +    url = f"""{os.environ.get("API_URL")}/upgrading?app_id=
Also, instead of using the `f"` style of string placeholders, let's use the "".format() style. It's the more modern way of doing it in python, especially with this many placeholders.

2021-02-18 21:34 UTC, katiemcgoff requested changes
as noted

2021-02-19 00:16 UTC, katiemcgoff commented on main.py
> +    app.run(debug=True, host="0.0.0.0", port=int(os.environ.get("PORT", 3001)))
Let's not check this change in, it doesn't apply to everyone. Or discuss with the team re. changing it. I understand it conflicts with the react app.

2021-02-19 00:20 UTC, DawsonDease commented on main.py
> +    app.run(debug=True, host="0.0.0.0", port=int(os.environ.get("PORT", 3001)))
damn I didn't mean to upload this. Ill take it out

2021-02-19 03:00 UTC, katiemcgoff approved these changes

2021-02-19 17:03 UTC, JaycobDuffel approved these changes

2021-02-19 17:22 UTC, merged